Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
import numpy as np

# Task 1: Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("Empty array:\n", empty_array)

# Task 2: Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))
print("\nOnes array:\n", ones_array)

# Task 3: Return a new array of given shape and type, filled with fill value.
shape = (3, 3)
fill_value = 7
full_array = np.full(shape, fill_value)
print("\nFull array:\n", full_array)


# Task 4: Return a new array of zeros with same shape and type as a given array.
example_array = np.array([[1, 2], [3, 4]], dtype=np.int32)
zeros_like_array = np.zeros_like(example_array)
print("\nZeros like array:\n", zeros_like_array)

# Task 5: Return a new array of ones with same shape and type as a given array.
ones_like_array = np.ones_like(example_array)
print("\nOnes like array:\n", ones_like_array)

# Task 6: Convert a list to a NumPy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy array from list:\n", numpy_array)

Empty array:
 [[5.01813074e-310 0.00000000e+000]
 [6.86317099e-310 6.86323211e-310]]

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like array:
 [[0 0]
 [0 0]]

Ones like array:
 [[1 1]
 [1 1]]

Numpy array from list:
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.




In [ ]:
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49.
arr1 = np.arange(10, 50)
print("Array with values from 10 to 49:\n", arr1)

# Task 2: Create a 3x3 matrix with values ranging from 0 to 8.
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:\n", arr2)

# Task 3: Create a 3x3 identity matrix.
arr3 = np.eye(3)
print("\n3x3 identity matrix:\n", arr3)

# Task 4: Create a random array of size 30 and find the mean.
arr4 = np.random.random(30)
mean_arr4 = arr4.mean()
print("\nRandom array of size 30:\n", arr4)
print("\nMean of the array:\n", mean_arr4)

# Task 5: Create a 10x10 array with random values and find min/max.
arr5 = np.random.random((10, 10))
min_arr5 = arr5.min()
max_arr5 = arr5.max()
print("\n10x10 array with random values:\n", arr5)
print("\nMinimum value:\n", min_arr5)
print("\nMaximum value:\n", max_arr5)

# Task 6: Create a zero array of size 10 and replace the 5th element with 1.
arr6 = np.zeros(10)
arr6[4] = 1  # 5th element (index 4)
print("\nZero array with 5th element replaced by 1:\n", arr6)

# Task 7: Reverse an array.
arr7 = [1, 2, 0, 0, 4, 0]
reversed_arr7 = arr7[::-1]
print("\nReversed array:\n", reversed_arr7)

# Task 8: Create a 2D array with 1 on the border and 0 inside.
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", arr8)

# Task 9: Create an 8x8 matrix with a checkerboard pattern.
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n8x8 matrix with checkerboard pattern:\n", arr9)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.9813732  0.03077841 0.14530023 0.70690832 0.89448761 0.08893751
 0.47961437 0.29688336 0.28102264 0.34030263 0.15385176 0.32702617
 0.33861883 0.58809502 0.8091756  0.25425135 0.85927426 0.87305407
 0.44722627 0.18043116 0.41977672 0.56811681 0.35195991 0.5353045
 0.08719268 0.17461839 0.80069201 0.13273484 0.10690025 0.21026648]

Mean of the array:
 0.4154725113606832

10x10 array with random values:
 [[0.39781822 0.15379897 0.7047414  0.49737824 0.26944881 0.04487358
  0.79562393 0.21521135 0.27571524 0.77471758]
 [0.14675924 0.94022239 0.15390583 0.16566405 0.03462308 0.32931292
  0.60915498 0.68649988 0.68567367 0.3415107 ]
 [0.99815452 0.51718152 0.18552832 0.83909672 0.076

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
print("Sum of x and y:\n",np.add(x,y))

#2. Subtract the two arrays
print("\nDifference of x and y:\n",np.subtract(x,y))

# 3. Multiply the array with an integer
print("\nx multiplied by 2:\n",x*2)
print("\ny multiplied by 5:\n",y*5)


# 4. Find the square of each element
print("\nSquare of x:\n",np.square(x))
print("\nSquare of y:\n",np.square(y))


# 5. Dot product
print("\nDot product of v and w:",np.dot(v,w))
print("\nDot product of x and v:\n",np.dot(x,v))
print("\nDot product of x and y:\n",np.dot(x,y))


# 6. Concatenate
print("\nConcatenate x and y along rows:\n",np.concatenate((x,y),axis=0)) #row wise
print("\nConcatenate v and w along columns:\n",np.concatenate((v[:,np.newaxis],w[:,np.newaxis]),axis=1)) #column wise, need to reshape v and w first

# 7. Concatenate x and v
# print("\nConcatenate x and v:\n",np.concatenate((x,v),axis=0))
# The above code will throw an error because x and v do not have the same number of dimensions.
# x is a 2D array (2 rows, 2 columns)
# v is a 1D array (2 elements)
# When concatenate along axis=0 (row wise) both array should have same number of column
# To concatenate, the arrays need to have compatible dimensions.
# One way to fix is this.
print("\nConcatenate x and v:\n",np.concatenate((x,v.reshape(1,2)),axis=0))

Sum of x and y:
 [[ 6  8]
 [10 13]]

Difference of x and y:
 [[-4 -4]
 [-4 -3]]

x multiplied by 2:
 [[ 2  4]
 [ 6 10]]

y multiplied by 5:
 [[25 30]
 [35 40]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Square of y:
 [[25 36]
 [49 64]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Concatenate x and v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

# Problem - 1: Array Creation (already provided in the original code)

# ... (Existing code for array creation tasks) ...


# Problem 2: Matrix Operations

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("\nA * A⁻¹:\n", I)  # Should be close to the identity matrix due to floating point precision

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB ≠ BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = np.transpose(AB)
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)

print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)
print("\n(AB)ᵀ = BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))


# Solving System of Linear Equations

# Represent the equations in matrix form AX = B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve for X using inverse method
X = np.dot(np.linalg.inv(A), B)
print("\nSolution using inverse method:\n", X)

# Solve using np.linalg.solve
X_solve = np.linalg.solve(A,B)
print("\nSolution using np.linalg.solve:\n", X_solve)


A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB ≠ BA: True

(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ = BᵀAᵀ: True

Solution using inverse method:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


In [ ]:
import time
import numpy as np

# Python Lists
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

print(f"Time taken for list element-wise addition: {end_time - start_time} seconds")


# NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
array_sum = array1 + array2
end_time = time.time()

print(f"Time taken for NumPy array element-wise addition: {end_time - start_time} seconds")

In [ ]:
import numpy as np
import time

# Python Lists
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

print(f"Time taken for list element-wise multiplication: {end_time - start_time} seconds")


# NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print(f"Time taken for NumPy array element-wise multiplication: {end_time - start_time} seconds")

In [ ]:
# prompt: Dot Product
# • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
# Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
# operation.

import numpy as np
import time

# Python Lists Dot Product
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()

print(f"Dot product (Python Lists): {dot_product_list}")
print(f"Time taken (Python Lists): {end_time - start_time} seconds")

# NumPy Arrays Dot Product
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()

print(f"Dot product (NumPy Arrays): {dot_product_array}")
print(f"Time taken (NumPy Arrays): {end_time - start_time} seconds")

In [ ]:
import numpy as np
import time

# Python Lists Matrix Multiplication
def matrix_multiply_lists(A, B):
  rows_A = len(A)
  cols_A = len(A[0])
  rows_B = len(B)
  cols_B = len(B[0])

  if cols_A != rows_B:
    raise ValueError("Matrices cannot be multiplied")

  result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
  for i in range(rows_A):
    for j in range(cols_B):
      for k in range(cols_A):
        result[i][j] += A[i][k] * B[k][j]
  return result

# NumPy Arrays Matrix Multiplication
def matrix_multiply_numpy(A, B):
  return np.dot(A, B)

# Matrix sizes
size = 1000

# Initialize matrices using lists
matrix_A_list = [[j for j in range(size)] for i in range(size)]
matrix_B_list = [[j for j in range(size)] for i in range(size)]

# Initialize matrices using NumPy arrays
matrix_A_np = np.random.rand(size, size)
matrix_B_np = np.random.rand(size, size)


# Python Lists
start_time = time.time()
result_list = matrix_multiply_lists(matrix_A_list, matrix_B_list)
end_time = time.time()
print(f"Time taken for Python lists matrix multiplication: {end_time - start_time} seconds")

# NumPy Arrays
start_time = time.time()
result_np = matrix_multiply_numpy(matrix_A_np, matrix_B_np)
end_time = time.time()
print(f"Time taken for NumPy arrays matrix multiplication: {end_time - start_time} seconds")